### ISSUE TITLE
Bosh agent paniced during host routing parsing

### ISSUE THREAD

**Issue by hanlins** [cloudfoundry/bosh-agent#230]
# Environment
Stemcell: `bosh-azure-hyperv-ubuntu-xenial-go_agent/621.59`
Opsman: `v2.8.5-build.234`

# Description
Deploying `calico` in a kubernetes cluster as pod network solution. Calico will deploy `calico-node` on worker VMs as a daemon set, which will modify the VM network setting (adding tunneling interface, add routes). As the VM host routing got modified, bosh agent failed parsing host routing, and emit following panic logs in agent log (at `/var/vcap/bosh/log/current`):
```
22:05:43 DEBUG - Successful: true (0)
2020-03-26_22:05:43.90478 panic: runtime error: index out of range [0] with length 0
2020-03-26_22:05:43.90481
2020-03-26_22:05:43.90481 goroutine 18 [running]:
2020-03-26_22:05:43.90481 github.com/cloudfoundry/bosh-agent/platform/net.parseRoute(0xc0002b034c, 0x28, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
2020-03-26_22:05:43.90482 	/tmp/build/9674af12/gopath/src/github.com/cloudfoundry/bosh-agent/platform/net/routes_searcher_unix.go:29 +0x425
2020-03-26_22:05:43.90482 github.com/cloudfoundry/bosh-agent/platform/net.cmdRoutesSearcher.SearchRoutes(0xbd3680, 0xc000166770, 0xaa7760, 0xc0001a68c0, 0xc0001a6958, 0x989833, 0x2)
2020-03-26_22:05:43.90482 	/tmp/build/9674af12/gopath/src/github.com/cloudfoundry/bosh-agent/platform/net/routes_searcher_unix.go:60 +0x19e
2020-03-26_22:05:43.90482 github.com/cloudfoundry/bosh-agent/platform/net.defaultNetworkResolver.GetDefaultNetwork(0xbbf9c0, 0xc000166820, 0xbbfa80, 0xafba58, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
2020-03-26_22:05:43.90484 	/tmp/build/9674af12/gopath/src/github.com/cloudfoundry/bosh-agent/platform/net/default_network_resolver.go:29 +0xa5
2020-03-26_22:05:43.90484 github.com/cloudfoundry/bosh-agent/platform.linux.GetDefaultNetwork(...)
2020-03-26_22:05:43.90484 	/tmp/build/9674af12/gopath/src/github.com/cloudfoundry/bosh-agent/platform/linux_platform.go:1371
2020-03-26_22:05:43.90484 github.com/cloudfoundry/bosh-agent/settings.(*settingsService).resolveNetwork(0xc00019c480, 0xc000219530, 0x6, 0xc000219536, 0xa, 0xc000219540, 0xd, 0xc000219557, 0x9, 0x100, ...)
2020-03-26_22:05:43.90486 	/tmp/build/9674af12/gopath/src/github.com/cloudfoundry/bosh-agent/settings/service.go:249 +0x80
2020-03-26_22:05:43.90486 github.com/cloudfoundry/bosh-agent/settings.(*settingsService).GetSettings(0xc00019c480, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
2020-03-26_22:05:43.90489 	/tmp/build/9674af12/gopath/src/github.com/cloudfoundry/bosh-agent/settings/service.go:226 +0x424
2020-03-26_22:05:43.90490 github.com/cloudfoundry/bosh-agent/agent.bootstrap.Run(0xbddb40, 0xc000178000, 0xbe2240, 0xc0001cc000, 0xacb9b7, 0x9, 0xbd58a0, 0xc00019c480, 0xbcc8a0, 0xc000174960, ...)
2020-03-26_22:05:43.90492 	/tmp/build/9674af12/gopath/src/github.com/cloudfoundry/bosh-agent/agent/bootstrap.go:71 +0x124
2020-03-26_22:05:43.90493 github.com/cloudfoundry/bosh-agent/app.(*app).Setup(0xc00017a000, 0x0, 0x0, 0x7ffd554ecf22, 0x6, 0xacb9b7, 0x9, 0xac8136, 0x5, 0x7ffd554ecf2c, ...)
2020-03-26_22:05:43.90495 	/tmp/build/9674af12/gopath/src/github.com/cloudfoundry/bosh-agent/app/app.go:120 +0x9f2
2020-03-26_22:05:43.90496 main.runAgent.func1(0xbd71c0, 0xc00014a2a0, 0x0, 0x0, 0x7ffd554ecf22, 0x6, 0xacb9b7, 0x9, 0xac8136, 0x5, ...)
2020-03-26_22:05:43.90499 	/tmp/build/9674af12/gopath/src/github.com/cloudfoundry/bosh-agent/main/agent.go:35 +0x259
2020-03-26_22:05:43.90511 created by main.runAgent
2020-03-26_22:05:43.90511 	/tmp/build/9674af12/gopath/src/github.com/cloudfoundry/bosh-agent/main/agent.go:23 +0xb9
```

As agent failed sending heart beat to director, director consider the VM as failed and resurrect the VM.
```
master/04829d8e-61c8-4c1a-958d-2e1b774ff315  running             zone-2  10.0.16.12  agent_id:c815c108-4fb4-4e42-b7ad-d346be38c5e5;resource_group_name:ember-mistress  Standard_F4s  true    bosh-azure-hyperv-ubuntu-xenial-go_agent/621.59
master/b63d4f59-fbda-42a6-a803-d88fb9dab944  running             zone-3  10.0.16.13  agent_id:9cbe2eeb-3a58-4978-a631-88d87093b7f7;resource_group_name:ember-mistress  Standard_F4s  true    bosh-azure-hyperv-ubuntu-xenial-go_agent/621.59
master/ef62a602-49af-450f-8844-5cb222e3d319  running             zone-1  10.0.16.11  agent_id:4037c4f6-47c6-41ef-8c91-5b2d5866f325;resource_group_name:ember-mistress  Standard_F4s  true    bosh-azure-hyperv-ubuntu-xenial-go_agent/621.59
worker/8f093c3d-6a1a-4b7f-9377-f03aac3fb2de  unresponsive agent  zone-2  10.0.16.15  agent_id:a2d4d759-adcc-4dc8-81a7-9e846d2dd88d;resource_group_name:ember-mistress  Standard_F4s  true    bosh-azure-hyperv-ubuntu-xenial-go_agent/621.59
worker/9d3ca82c-6792-4201-9ae7-e78c821aab5e  unresponsive agent  zone-3  10.0.16.16  agent_id:dc5094a5-1b29-4148-90ab-c43b40bd8fe1;resource_group_name:ember-mistress  Standard_F4s  true    bosh-azure-hyperv-ubuntu-xenial-go_agent/621.59
worker/c7883874-9b77-4aae-81a9-368941bb23cc  unresponsive agent  zone-1  10.0.16.14  agent_id:15a91e9b-745c-4134-831a-0f059ddd1b84;resource_group_name:ember-mistress  Standard_F4s  true    bosh-azure-hyperv-ubuntu-xenial-go_agent/621.59
```

## VM network information
The `ip r` result on the VM is followed:
```
/c7883874-9b77-4aae-81a9-368941bb23cc:~# ip r
default via 10.0.16.1 dev eth0  proto dhcp  src 10.0.16.14  metric 1024
default via 10.0.16.1 dev eth0  proto dhcp  metric 1024
10.0.16.0/22 dev eth0  proto kernel  scope link  src 10.0.16.14
10.0.16.1 dev eth0  proto dhcp  scope link  src 10.0.16.14  metric 1024
10.200.30.192/26 via 10.0.16.15 dev tunl0  proto bird onlink
blackhole 10.200.115.192/26  proto bird
168.63.129.16 via 10.0.16.1 dev eth0  proto dhcp  metric 1024
169.254.169.254 via 10.0.16.1 dev eth0  proto dhcp  metric 1024
172.17.0.0/16 dev docker0  proto kernel  scope link  src 172.17.0.1 linkdown
```

**Comment by hanlins** [comment]
The `RouteList` method in `github.com/vishvananda/netlink` is similar to the `SearchRoutes` functionality for unix, seems like reinvent the wheel.

**Comment by hanlins** [comment]
The root cause of the panic is route:
```
blackhole 10.200.115.192/26  proto bird
```

Added checking and error handling to avoid the runtime panic.

**Comment by aashah** [comment]
PR was merged, closing issue out.
